services:
  - type: web
    name: recommendme-backend
    runtime: python
    buildCommand: ""
    startCommand: python app.py
    envVars:
      - key: PYTHON_VERSION
        value: 3.9services:
  - type: web
    name: recommendme-backend
    runtime: python
    buildCommand: ""
    startCommand: gunicorn app:app --bind 0.0.0.0:$PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.9
